title: Starward Odyssey
permalink: pretty
description: A Space Adventure Game
theme: just-the-docs
url: https://starwardodyssey.com/
# logo: 
color_scheme: dark

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

footer_content: "The text on this page is licensed under <a href=\"https://creativecommons.org/licenses/by-sa/4.0\">CC-BY-SA 4.0.</a>"
