title: Starward Odyssey
permalink: pretty
description: A Space Adventure Game
theme: just-the-docs
url: https://starwardodyssey.com/
# logo: 
color_scheme: dark
nav_enabled: true

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Starward Odyssey SRD by <a href=\"https://eucatastrophic.itch.io/"Jason Christopher Burrows" is licensed under <a href=\"https://creativecommons.org/licenses/by-sa/4.0\">CC-BY-SA 4.0.</a>"
