title: Starward Odyssey
description: A Space Adventure Game
theme: just-the-docs

url: https://theeucatastrophe.github.io/starwardodyssey/

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/TheEucatastrophe/starwardodyssey
